"""
tools/detect_flaky_tests.py
Nondeterminism detector — run tests repeatedly, flag inconsistent results.

Usage:
    python tools/detect_flaky_tests.py tests/test_determinism.py --runs 5
    python tools/detect_flaky_tests.py tests/test_foo.py::TestBar::test_x --runs 3
    python tools/detect_flaky_tests.py --auto   # run all tests 3 times

Generates:
    docs/FLAKY_TEST_REPORT.md
"""
from __future__ import annotations

import argparse
import json
import logging
import re
import subprocess
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

REPO_ROOT   = Path(__file__).resolve().parent.parent
DOCS_DIR    = REPO_ROOT / "docs"
REPORT_FILE = DOCS_DIR / "FLAKY_TEST_REPORT.md"

JST = timezone(timedelta(hours=9))

logging.basicConfig(
    level=logging.INFO,
    format="[FLAKY_DETECT] %(levelname)s %(message)s",
)
logger = logging.getLogger(__name__)


def _run_pytest_once(
    test_targets: list[str],
    extra_args: list[str] | None = None,
) -> dict[str, bool]:
    """
    Run pytest on targets, return {test_id: passed} map.
    Uses -v --tb=no for clean output parsing.
    """
    cmd = [
        sys.executable, "-m", "pytest",
        "--tb=no", "-v", "--no-header", "-q",
    ] + test_targets + (extra_args or [])

    result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(REPO_ROOT))
    output = result.stdout + result.stderr

    outcomes: dict[str, bool] = {}
    for line in output.splitlines():
        # pytest -v output: "tests/foo.py::Bar::test_x PASSED"
        if " PASSED" in line:
            test_id = line.split(" PASSED")[0].strip()
            if "::" in test_id:
                outcomes[test_id] = True
        elif " FAILED" in line:
            test_id = line.split(" FAILED")[0].strip()
            if "::" in test_id:
                outcomes[test_id] = False
        elif " ERROR" in line:
            test_id = line.split(" ERROR")[0].strip()
            if "::" in test_id:
                outcomes[test_id] = False

    return outcomes


def run_flaky_detection(
    test_targets: list[str],
    n_runs: int = 5,
    extra_args: list[str] | None = None,
) -> dict[str, list[bool]]:
    """
    Run test_targets n_runs times. Return {test_id: [pass_run1, pass_run2, ...]}.
    """
    all_results: dict[str, list[bool]] = {}

    for run_i in range(n_runs):
        logger.info("Run %d/%d ...", run_i + 1, n_runs)
        outcomes = _run_pytest_once(test_targets, extra_args)
        for test_id, passed in outcomes.items():
            all_results.setdefault(test_id, []).append(passed)

    return all_results


def classify_results(
    results: dict[str, list[bool]],
) -> tuple[list[str], list[str], list[str]]:
    """
    Classify tests into:
        flaky:        both pass and fail observed
        always_pass:  all runs passed
        always_fail:  all runs failed

    Returns (flaky_ids, always_pass_ids, always_fail_ids)
    """
    flaky:        list[str] = []
    always_pass:  list[str] = []
    always_fail:  list[str] = []

    for test_id, outcomes in results.items():
        unique = set(outcomes)
        if len(unique) > 1:
            flaky.append(test_id)
        elif True in unique:
            always_pass.append(test_id)
        else:
            always_fail.append(test_id)

    return sorted(flaky), sorted(always_pass), sorted(always_fail)


def generate_report(
    results: dict[str, list[bool]],
    n_runs: int,
    test_targets: list[str],
) -> str:
    now = datetime.now(JST).strftime("%Y-%m-%dT%H:%M:%S%z")
    flaky, always_pass, always_fail = classify_results(results)

    total   = len(results)
    n_flaky = len(flaky)
    status_label = "CLEAN" if n_flaky == 0 else f"{n_flaky} FLAKY"
    status_emoji = "✅" if n_flaky == 0 else "⚠️"

    flaky_rows = "\n".join(
        "| {id} | {outcomes} | {rate:.0%} |".format(
            id=tid,
            outcomes=" ".join("P" if p else "F" for p in results[tid]),
            rate=sum(results[tid]) / len(results[tid]),
        )
        for tid in flaky
    ) or "_None detected._"

    always_fail_rows = "\n".join(f"- `{tid}`" for tid in always_fail) or "_None._"

    return f"""# FLAKY_TEST_REPORT.md — CHIBAAssetProject
> **Generated**: {now}
> Auto-generated by `tools/detect_flaky_tests.py`. Do not edit manually.

---

## Result: {status_emoji} {status_label}

- **Runs per test**: {n_runs}
- **Tests analysed**: {total}
- **Flaky tests**: {n_flaky}
- **Always failing**: {len(always_fail)}
- **Always passing**: {len(always_pass)}

Targets: `{", ".join(test_targets) or "all"}`

---

## Flaky Tests (nondeterministic)

| Test ID | Run sequence (P=pass F=fail) | Pass rate |
|---------|------------------------------|-----------|
{flaky_rows}

---

## Always-Failing Tests

{always_fail_rows}

---

## How to Fix Flaky Tests

1. Add `from src.governance.determinism import set_deterministic` at test start
2. Remove wall-clock dependencies — use `FixedClock` instead of `datetime.now()`
3. Isolate filesystem state — use `tmp_path` fixture
4. Remove race conditions — avoid threading in tests

```bash
# Re-run detection:
python tools/detect_flaky_tests.py tests/ --runs 5
```
"""


def _cli() -> None:
    parser = argparse.ArgumentParser(
        description="Detect flaky/nondeterministic tests"
    )
    parser.add_argument("targets", nargs="*", help="Test paths or IDs (default: tests/)")
    parser.add_argument("--runs",       type=int, default=3, help="Number of runs (default: 3)")
    parser.add_argument("--no-report",  action="store_true", help="Skip writing FLAKY_TEST_REPORT.md")
    parser.add_argument("--auto",       action="store_true", help="Run all tests/ directory")
    args = parser.parse_args()

    if args.auto or not args.targets:
        targets = [str(REPO_ROOT / "tests")]
    else:
        targets = args.targets

    results = run_flaky_detection(targets, n_runs=args.runs)
    flaky, _, _ = classify_results(results)

    report = generate_report(results, n_runs=args.runs, test_targets=targets)

    if not args.no_report:
        DOCS_DIR.mkdir(parents=True, exist_ok=True)
        REPORT_FILE.write_text(report, encoding="utf-8")
        logger.info("Report written: %s", REPORT_FILE)

    if flaky:
        logger.error("FLAKY TESTS DETECTED (%d):", len(flaky))
        for tid in flaky:
            logger.error("  %s", tid)
        sys.exit(1)

    logger.info("No flaky tests detected across %d run(s).", args.runs)


if __name__ == "__main__":
    _cli()
